#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define CANTIDAD_ESTADOS 7

typedef enum {
	CLOSE_CONNECTION, // tiene que ser 0
	// Sockets
	HANDSHAKE_CONSOLA,
	HANDSHAKE_KERNEL,
	HANDSHAKE_MEMORIA,
	HANDSHAKE_CPU,
	// Consola
	INSTRUCCIONES,
	FINALIZACION_CONSOLA,
    // CPU
    INTERRUPCION,
    EJECUTAR_PROCESO,
    DEVOLVER_PROCESO,
    // MEMORIA
    INICIAR_PROCESO,
    SUSPENDER_PROCESO,
    FINALIZAR_PROCESO,
    PEDIR_TABLA,
    PEDIR_MARCO,
    LEER_MARCO,
    MEMORIA_LEER,
    MEMORIA_ESCRIBIR,
    ESCRITURA_OK,
    ESCRITURA_ERROR
} op_code;

typedef enum {
	NEW, READY, EXEC, BLOCKED, EXIT, SUSPENDED_READY, SUSPENDED_BLOCKED
} t_estado;

typedef enum {
	FIFO, SRT, LRU, CLOCK, CLOCK_M
} t_algoritmo;

#endif
