#ifndef CONSTANTES_H_
#define CONSTANTES_H_

#define NEW 0
#define EXEC 1
#define BLOCKED 2
#define READY 3
#define EXIT 4 // IMPORTANTE QUE SEA EL NUMERO MAS GRANDE DE LOS ESTADOS

typedef enum {
	INICIAR_PLANIFICACION,
	PAUSAR_PLANIFICACION,
	OBTENER_BITACORA,
	INICIAR_PATOTA,
	LISTAR_TRIPULANTES,
	EXPULSAR_TRIPULANTE,
	INICIAR_TRIPULANTE,
	MOVER_TRIPULANTE,
	PROXIMA_TAREA,
	AGREGAR_ACCION,
	SABOTAJE,
	INICIAR_FSCK,
	CAMBIAR_ESTADO,
	FIN_TAREAS,
	HANDSHAKE_DISCORDIADOR
} op_code;

static const char const char_estados[] = {
	[NEW] = 'N',
	[EXEC] = 'E',
	[BLOCKED] = 'B',
	[READY] = 'R',
	[EXIT] = 'X' // NO SE USA CREO
};

static const char* const string_estados[] = {
	[NEW] = "NEW",
	[EXEC] = "EXECUTE",
	[BLOCKED] = "BLOCKED",
	[READY] = "READY",
	[EXIT] = "EXIT"
};

typedef enum {
	GENERAR_OXIGENO,
	CONSUMIR_OXIGENO,
	GENERAR_COMIDA,
	CONSUMIR_COMIDA,
	GENERAR_BASURA,
	DESCARTAR_BASURA
} tarea_io;

static const char* const tareas_io[] = {
	[GENERAR_OXIGENO] = "GENERAR_OXIGENO",
	[CONSUMIR_OXIGENO] = "CONSUMIR_OXIGENO",
	[GENERAR_COMIDA] = "GENERAR_COMIDA",
	[CONSUMIR_COMIDA] = "CONSUMIR_COMIDA",
	[GENERAR_BASURA] = "GENERAR_BASURA",
	[DESCARTAR_BASURA] = "DESCARTAR_BASURA"
};

#endif